<a href="https://colab.research.google.com/github/renatagomezc/Extraccion-de-datos/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO .CSV

In [3]:
#Convertir en dataframe
#df= pd.read_csv("file.csv")
#df

CARGA DE ARCHIVO XLSX

In [4]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx')
#df

In [7]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. CLIENTE        164 non-null    object
 1   NOMBRE             164 non-null    object
 2   FACTURA            164 non-null    object
 3   FECHA_FACTURA      164 non-null    datetime64[ns]
 4   FECHA_VENCIMIENTO  164 non-null    datetime64[ns]
 5   MONTO ADEUDADO     164 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 7.8+ KB

In [6]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [8]:
#Filtro por objeto 
filtro1=df[df["NOMBRE"] == "INDUSTRIAS LANCERMEX"]
filtro1

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82

In [13]:
#Filtro por filas
#filtro2= df.iloc[3:10,: ]           #Filas consecutivas
filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas 
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
8,644,CLAVOS NACIONALES C.N,F40340,2023-03-13,2023-05-12,45216.34
24,8708,TE.MEX AUTOMOTIVE,F40183,2023-02-20,2023-03-13,22956.40
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16

In [15]:
#Filtro por columnas
filtro3=df.iloc[ : , 1:3]       #Columnas consecutivas 
#filtro3=df.iloc[ : , [1,4,6]]  #Columnas no consecutivas 
filtro3

                                                NOMBRE  FACTURA
0                                 DONGA HWASUNG MEXICO   F40238
1                                 DONGA HWASUNG MEXICO   F40353
2         PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO   F40352
3                                 INDUSTRIAS LANCERMEX   F40217
4                                               HELVEX   F40173
..                                                 ...      ...
159  CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...   F40055
160                                 PÚBLICO EN GENERAL  NV00777
161                                 PÚBLICO EN GENERAL  NV00778
162                                 PÚBLICO EN GENERAL  NV00779
163                                  FISHERS QUERETARO   F38248

[164 rows x 2 columns]

In [16]:
#Filtro de filas vs columnas 
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

Saving Antigüedad de saldos 17.03.2023.xlsx to Antigüedad de saldos 17.03.2023 (2).xlsx

In [17]:
df1= pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx', index_col=1)
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
PÚBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
PÚBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
PÚBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

In [18]:
#Paso 2: Aplicamos Filtro de filas vs columnas 
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [19]:
#Filtro por cabecera
filtro5=df.head(10)
filtro5

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
5,1429,AUTOLIV STEERING WHEELS MEXICO,F39979,2023-01-24,2023-03-25,49416.00
6,1429,AUTOLIV STEERING WHEELS MEXICO,F40319,2023-03-08,2023-05-07,49416.00
7,5039,BUSSMANN,F40082,2023-02-04,2023-02-04,48882.12
8,644,CLAVOS NACIONALES C.N,F40340,2023-03-13,2023-05-12,45216.34
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [20]:
#Filtro por comparacion
filtro6=df[df["MONTO ADEUDADO"] > 70000]
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94

**FILTROS BASICOS CON CONETORES LOGICOS**

In [21]:
#Filtro Y Tiene que cumplir las dos condiciones
filtro7=df[(df["MONTO ADEUDADO"] < 6000) & (df["FECHA_FACTURA"] == "2023-03-14")]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
85,409,CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS IN...,F40359,2023-03-14,2023-03-14,4292.00
96,3926,PRODUCTOS PENNSYLVANIA,F40358,2023-03-14,2023-04-13,3368.64
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,PÚBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96

In [22]:
#Filtro o
filtro8=df[(df["MONTO ADEUDADO"] < 6000) | (df["FECHA_FACTURA"] == "2023-03-14")]
filtro8

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
36,417,COVEMEX,F40354,2023-03-14,2023-03-29,15843.28
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [23]:
#Filtro not
filtro9=df[~(df["MONTO ADEUDADO"] >= 6000) & ~(df["FECHA_FACTURA"] == "2023-03-14")]
filtro9

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
70,1852,ITW POLY MEX,F40201,2023-02-22,2023-03-24,5967.85
71,8316,ANA BARBARA CRUZ PALACIOS,F40379,2023-03-16,2023-03-31,5827.84
72,8787,ARMANDO VIDAURRETA PEÑA,F39769,2022-12-14,2022-12-14,5800.00
73,2768,CEREALES Y PASTAS,F40215,2023-02-22,2023-03-24,5660.80
74,1831,DISTRIBUCIONES Y REPRESENTACIONES CALORA,F40316,2023-03-08,2023-04-22,5502.81
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [24]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("Entregable1.csv")

In [ ]:
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("Entregable1.csv")